#!/bin/bash

echo -e "${TXT_YELLOW}- backup files -${TXT_CLEAR}"
ssh -p 122 -i $DEPLOY_SSH_KEY $DEPLOY_USER@$DEPLOY_IP "mkdir -p $DEPLOY_BACKUP_PATH"
ssh -p 122 -i $DEPLOY_SSH_KEY $DEPLOY_USER@$DEPLOY_IP "cp -r $APP_PATH $DEPLOY_BACKUP_PATH"

echo -e "${TXT_YELLOW}- upload files -${TXT_CLEAR}"
ssh -p 122 -i $DEPLOY_SSH_KEY $DEPLOY_USER@$DEPLOY_IP "mkdir -p $APP_PATH"
scp -P 122 -i $DEPLOY_SSH_KEY $DEPLOY_USER@$DEPLOY_IP *.py Dockerfile Makefile requirements.txt $DEPLOY_USER@$DEPLOY_IP:$APP_PATH

echo -e "${TXT_YELLOW}- make up docker -${TXT_CLEAR}"
ssh -p 122 -i $DEPLOY_SSH_KEY $DEPLOY_USER@$DEPLOY_IP "cd $APP_PATH && CONFIG_FILE=$CONFIG_FILE APP_CONFIG_PATH=$APP_CONFIG_PATH APP_PORT=$APP_PORT APP_IDENTIFIER=$APP_IDENTIFIER APP_LOG_PATH=$APP_LOG_PATH make up"
